language: node_js

dist: focal

addons:
  chrome: stable

node_js:
  - '14'

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm test
  - npm run build
